Adding pip_unpie which unflags DT_PIE_1 ELF flag to be applied to the created binary by pipcc
Conflicts:
	bin/Makefile
	bin/pipcc.in

diff --git a/bin/pip-check.in b/bin/pip-check.in
--- a/bin/pip-check.in
+++ b/bin/pip-check.in
@@ -48,17 +48,19 @@
 ### \sa pipcc
 ###
 
+HAVE_PIPGLIBC=@have_pipglibc@
+
 ldso="@dynamic_linker@"
 
 prog=$0;
 
 show_usage () {
-    echo "$0 [-r|-t|-b|-v|-h] a.out ..." > /dev/stderr;
-    echo "  -r: check if a.out can be PiP root" > /dev/stderr;
-    echo "  -t: check if a.out can be PiP task" > /dev/stderr;
-    echo "  -b: check if a.out can be PiP root and/or PiP task" > /dev/stderr;
-    echo "  -v: show reason" > /dev/stderr;
-    echo "  -h: show this message" > /dev/stderr;
+    echo >&2 "$0 [-r|-t|-b|-v|-h] a.out ...";
+    echo >&2 "  -r: check if a.out can be PiP root";
+    echo >&2 "  -t: check if a.out can be PiP task";
+    echo >&2 "  -b: check if a.out can be PiP root and/or PiP task";
+    echo >&2 "  -v: show reason";
+    echo >&2 "  -h: show this message";
     exit 1;
 }
 
@@ -75,7 +77,7 @@ show_msgs () {
     shift;
     for i; do
 	if [ "$i" != "" ]; then
-	    echo "$target :" $i > /dev/stderr;
+	    echo >&2 "$target :" $i;
 	fi
     done
 }
@@ -106,11 +108,11 @@ check () {
 	return 1;
     fi
 
-    if [ "$ldso" != "" ]; then
+    if ${HAVE_PIPGLIBC} && [ "$ldso" != "" ]; then
 	interp=`readelf -p .interp $target 2> /dev/null | sed -e "s/  \[     0\]  //" -e "1,2d" -e "4d"`;
 	if [ "$interp" != "$ldso" ]; then
 	    froot=false;
-	    reason_root="(root) 'ld.so' not specified (not linked with '--dynamic-linker' option)"
+	    reason_root="(root) 'ld-linux.so' is not set properly"
 	fi
     fi
     if ! readelf --dyn-syms $target 2> /dev/null | grep ' main' > /dev/null 2>&1; then
@@ -165,7 +167,7 @@ for i; do
 	    -v|--verbose)  	 flag_verbose=true;;
 	    -h|--usage)   	 show_usage;;
 	    --ldlinux|--ldso)	 echo ${ldso}; exit 0;;
-	    -*)		  	 echo "Invalid option" > /dev/stderr; exit 1;;
+	    -*)		  	 echo >&2 "Invalid option"; exit 1;;
 	    *)  	  	 files="${files} $i";;
 	esac
 done
diff --git a/bin/pipcc.in b/bin/pipcc.in
--- a/bin/pipcc.in
+++ b/bin/pipcc.in
@@ -50,7 +50,7 @@
 ### \p \$(CC) is used to specify a C compiler
 ###
 ### \sa
-### pip-run(1), pip-mode(1)
+### pip-exec(1), pip-mode(1)
 ###
 
 # ${prefix} and ${exec_prefix} have to be lowercase,
@@ -59,8 +59,10 @@ prefix=@prefix@
 exec_prefix=@exec_prefix@
 PREFIX_INCDIR=@includedir@
 PREFIX_LIBDIR=@libdir@
+PREFIX_BINDIR=@bindir@
 SRCTOP=@srcdir_top@
 PIP_VERSION=@PACKAGE_VERSION@
+HAVE_PIPGLIBC=@have_pipglibc@
 
 glibc_incdir=@glibc_incdir@
 glibc_libdir=@glibc_libdir@
@@ -106,10 +108,12 @@ ccopts=false
 cflags=false
 lflags=false
 version=
+target=
 
 while [ "$1" != "" ]; do
     case $1 in
 	-c|-E|-S)  is_linking=false; opts="${opts} $1";;
+	-o)        shift; target=$1; opts="${opts} -o ${target}";;
 	--piproot|-piproot|--pip-root|-pip-root) pip_task=false;;
 	--piptask|-piptask|--pip-task|-pip-task) pip_root=false;;
 	--pipbuild) pipbuild=true;;
@@ -151,6 +155,15 @@ do_exec () {
     fi
 }
 
+do_run () {
+    if ! ${silent}; then
+	echo $@
+    fi
+    if ! ${dryrun}; then
+	$@
+    fi
+}
+
 if ${no_pip}; then
     do_exec ${CC} ${opts}
 fi
@@ -162,16 +175,20 @@ fi
 if ${pipinstall} ; then
     PIP_INCDIR="${PREFIX_INCDIR}"
     PIP_LIBDIR="${PREFIX_LIBDIR}"
+    PIP_BINDIR="${PREFIX_BINDIR}"
 elif ${pipbuild} ; then
     PIP_INCDIR=${SRCTOP}/include
     PIP_LIBDIR=${SRCTOP}/lib
+    PIP_BINDIR=${SRCTOP}/bin
 else
     if [ ${prefix}/bin/pipcc -ef ${self} ] ; then
 	PIP_INCDIR="${PREFIX_INCDIR}"
 	PIP_LIBDIR="${PREFIX_LIBDIR}"
+	PIP_BINDIR="${PREFIX_BINDIR}"
     elif [ ${SRCTOP}/bin/pipcc -ef ${self} ]; then
 	PIP_INCDIR=${SRCTOP}/include;
 	PIP_LIBDIR=${SRCTOP}/lib;
+	PIP_BINDIR=${SRCTOP}/bin
     else
 	echo >&2 "${cmd}: Failed to identify ${self}"
 	exit 1
@@ -206,7 +223,7 @@ fi
 GLIBC_CFLAGS=""
 GLIBC_LDFLAGS=""
 GLIBC_LDLINUX=""
-if [ x"${dynamic_linker}" != x"" ]; then
+if ${HAVE_PIPGLIBC} && [ x"${dynamic_linker}" != x"" ]; then
     case ${dynamic_linker} in
 	/lib/ld-*|/lib64/ld-*|/usr/lib/ld-*|/usr/lib64/ld-*) :;;
 	*)  GLIBC_CFLAGS="-I${glibc_incdir}";
@@ -272,19 +289,28 @@ fi
 if ${cflags} || ${lflags}; then
     # note that ${opts} will not be printed, unlike --ccopts (above)
     if ${cflags} && ${lflags}; then
-	echo ${PIPCC_DEFS} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${PIP_LDLIBS} \
-	    ${PIP_LDFLAGS} ${PIP_LDLIBS} ${FLAG_PTHREAD}
+	echo ${PIPCC_DEFS}  ${PIP_CFLAGS} ${PIP_LDFLAGS} ${PIP_LDLIBS} \
+	     ${PIP_LDFLAGS} ${PIP_LDLIBS} ${FLAG_PTHREAD}
     elif ${cflags}; then
-	echo ${PIPCC_DEFS} ${PIP_CFLAGS} ${FLAG_PTHREAD}
+	echo ${PIPCC_DEFS}  ${PIP_CFLAGS} ${FLAG_PTHREAD}
     else
 	echo ${PIP_LDFLAGS} ${PIP_LDLIBS} ${FLAG_PTHREAD}
     fi
     exit 0
 fi
 
+if [ x"${target}" == x ]; then
+    target="a.out"
+fi
+
 if ${is_linking}; then
-    do_exec ${CC} ${PIPCC_DEFS} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${PIP_LDLIBS} \
-	${FLAG_PTHREAD} ${opts}
+    do_run ${CC} ${PIPCC_DEFS} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${PIP_LDLIBS} \
+	   ${FLAG_PTHREAD} ${opts}
+    if [ -x ${PIP_BINDIR}/pip_unpie ]; then
+	${PIP_BINDIR}/pip_unpie ${target}
+    else
+	echo >&2 "${cmd} Warning: Unable to find and invoke ${PIP_BINDIR}/pip_unpie"
+    fi
 else
     do_exec ${CC} ${PIPCC_DEFS} ${PIP_CFLAGS} ${FLAG_PTHREAD} ${opts}
 fi
