Update license, copyright and author

diff --git a/bin/pipcc.in b/bin/pipcc.in
--- a/bin/pipcc.in
+++ b/bin/pipcc.in
@@ -1,20 +1,16 @@
 #!/bin/sh
 
-# $RIKEN_copyright: Riken Center for Computational Sceience (R-CCS),
-# System Software Development Team, 2016-2020
-# $
-# $PIP_VERSION: Version 2.0.0$
 # $PIP_license: <Simplified BSD License>
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
-# 
+#
 #     Redistributions of source code must retain the above copyright notice,
 #     this list of conditions and the following disclaimer.
-# 
+#
 #     Redistributions in binary form must reproduce the above copyright notice,
 #     this list of conditions and the following disclaimer in the documentation
 #     and/or other materials provided with the distribution.
-# 
+#
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 # AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 # IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
@@ -26,6 +22,13 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 # THE POSSIBILITY OF SUCH DAMAGE.
+# $
+# $RIKEN_copyright: Riken Center for Computational Sceience (R-CCS),
+# System Software Development Team, 2016-2020
+# $
+# $PIP_VERSION: Version 3.0.0$
+#
+# $Author: Atsushi Hori (R-CCS) mailto: ahori@riken.jp or ahori@me.com
 # $
 
 ### \page pipcc pipcc
@@ -46,12 +49,13 @@
 ### \environment
 ### if \p CC environment  is set then \p \$(CC) will be used as a C compiler
 ###
-### \sa pip-exec
-### \sa pip-mode
+### \sa
+### pip-exec(1), pip-mode(1)
 ###
 
 PREFIX=@prefix@
 SRCTOP=@srcdir_top@
+PIP_VERSION=@PACKAGE_VERSION@
 
 glibc_incdir=@glibc_incdir@
 glibc_libdir=@glibc_libdir@
@@ -61,10 +65,20 @@ dynamic_linker=@dynamic_linker@
 
 self=$0
 cmd=`basename ${self}`
+cmdline="$cmd $@"
+
+print_usage () {
+    echo >&2 "Error: ${cmdline}"
+    echo >&2 "${cmd} [PIP-OPTIONS] [CC-COMMAND-OPTIONS_AND_ARGS]"
+    echo >&2 "   --piproot: the compile (and link) as a PiP root"
+    echo >&2 "   --piptask: the compile (and link) as a PiP task"
+    echo >&2 "   --nopip:   No PiP related settings will be applied"
+    exit 2
+}
 
 err_nostatic() {
-    echo "${cmd} does not support static linking" >&2;
-    exit 1;
+    echo >&2 "${cmd} does not support static linking";
+    print_usage
 }
 
 is_linking=true
@@ -107,39 +121,50 @@ if ${no_pip}; then
     do_exec ${CC} ${opts}
 fi
 
-if $pipbuild ; then
-    PIP_INCDIR=${SRCTOP}/include
-    PIP_LIBDIR=${SRCTOP}/lib
-elif $pipinstall ; then
+if $pipinstall && $pipbuild ; then
+    print_usage
+fi
+
+if $pipinstall ; then
     PIP_INCDIR=${PREFIX}/include
     PIP_LIBDIR=${PREFIX}/lib
+    pipcc_path=${PREFIX}/bin/pipcc
+elif $pipbuild ; then
+    PIP_INCDIR=${SRCTOP}/include
+    PIP_LIBDIR=${SRCTOP}/lib
+    pipcc_path=${SRCTOP}/bin/pipcc
 else
-    if [ ${self} -ef ${PREFIX}/bin/pipcc ] ; then
+    if [ ${PREFIX}/bin/pipcc -ef ${self} ] ; then
 	PIP_INCDIR=${PREFIX}/include
 	PIP_LIBDIR=${PREFIX}/lib
-    elif [ ${self} -ef ${SRCTOP}/bin/pipcc ]; then
+	pipcc_path=${PREFIX}/bin/pipcc
+    elif [ ${SRCTOP}/bin/pipcc -ef ${self} ]; then
 	PIP_INCDIR=${SRCTOP}/include;
 	PIP_LIBDIR=${SRCTOP}/lib;
+	pipcc_path=${SRCTOP}/bin/pipcc
     else
-	echo "Unknown ${self}"
+	echo >&2 "${cmd}: Unknown ${self}"
 	exit 1
     fi
 fi
 
-if ! [ -f ${PIP_INCDIR}/pip.h ]; then
-    echo "Unable to find pip.h"
-    exit 1
-fi
-
 if ${which}; then
     ( cd ${PIP_LIBDIR}/../bin/; pipcc_path=`pwd`; echo "${pipcc_path}/pipcc" )
+    exit 0
 fi
 
 PIP_INCFLAGS="-I${PIP_INCDIR}"
 PIP_LDFLAGS="-L${PIP_LIBDIR} -Wl,-rpath=${PIP_LIBDIR}"
 PIP_LIB=${PIP_LIBDIR}/libpip.so
 
-PIP_VERSION_MAJOR=`grep PACKAGE_VERSION ${PIP_INCDIR}/pip_config.h | cut -d '.' -f 1`
+if [ -f ${PIP_INCDIR}/pip/pip_config.h ]; then
+    PIP_VERSION_MAJOR=`echo "${PIP_VERSION}" | cut -d '.' -f 1`
+    PIP_VERSION_MINOR=`echo "${PIP_VERSION}" | cut -d '.' -f 2`
+    PIP_VERSION_SUBMINOR=`echo "${PIP_VERSION}" | cut -d '.' -f 3`
+else
+    echo "${cmd}: Unable to find pip_config.h"
+    exit 1
+fi
 
 GLIBC_CFLAGS=""
 GLIBC_LDFLAGS=""
@@ -186,11 +211,15 @@ fi
 
 PTHREAD_FLAG="-pthread"
 
-PIPCC_DEF="-DPIPCC"
+PIPCC_DEFS="-DPIPCC \
+-DPIP_VERSION=${PIP_VERSION} \
+-DPIP_VERSION_MAJOR=${PIP_VERSION_MAJOR} \
+-DPIP_VERSION_MINOR=${PIP_VERSION_MINOR} \
+-DPIP_VERSION_SUBMINOR=${PIP_VERSION_SUBMINOR}"
 
 if ${is_linking}; then
-    do_exec ${CC} ${PIPCC_DEF} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${PIP_LDLIBS} \
+    do_exec ${CC} ${PIPCC_DEFS} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${PIP_LDLIBS} \
 	${PTHREAD_FLAG} ${opts}
 else
-    do_exec ${CC} ${PIPCC_DEF} ${PIP_CFLAGS} ${PTHREAD_FLAG} ${opts}
+    do_exec ${CC} ${PIPCC_DEFS} ${PIP_CFLAGS} ${PTHREAD_FLAG} ${opts}
 fi
