snapshot before blackout (pip_barrier does not work still ...)

diff --git a/bin/pipmode.in b/bin/pipmode.in
--- a/bin/pipmode.in
+++ b/bin/pipmode.in
@@ -36,80 +36,83 @@
 ###
 ### \section synopsis SYNOPSIS
 ###
-###	\c \b pipcc [<b>pip-options,\b>] [<b>cc-command-options</b>]
+###	\c \b pipenv [<b>pipenv-option\b>] [<b>commands ...</b>]
 ###
 ### \section options OPTIONS
 ###
 ### The following options are avilable. If no of them specified, then
 ### the compiled output file can be used as both PiP root and PiP task.
 ###
-### \subsection root -piproot
-### If specified, the compile (and link) is done for PiP root.
+### \subsection process	-P
+### If specified, PiP will run with the 'process' mode
 ###
-### \subsection task -piptask
-### If specified, the compile (and link) is done for PiP task
+### \subsection process	-p
+### If specified, PiP will run with the 'process' mode (preload)
+###
+### \subsection process	-c
+### If specified, PiP will run with the 'process' mode (pip clone)
+###
+### \subsection process	-T
+### If specified, PiP will run with the 'thread' mode
 ###
 
-prefix=@prefix@
-exec_prefix=@exec_prefix@
+self=$0;
+prefix=@prefix@;
+libdir=${prefix}/lib/;
+flag_help=0;
 
-includedir=@includedir@
-libdir=@libdir@
-dynamic_linker=@dynamic_linker@
-
-pip_root=true
-pip_task=true
-
-: ${CC:=cc}
-
-PIPC_CFLAGS="-I${includedir} -pthread"
-PIPC_LDFLAGS="-L${libdir} -Wl,-rpath=${libdir}"
-PIPC_LDLIBS="-lpip -ldl"
-
-PIPR_CFLAGS="${PIPC_CFLAGS}"
-PIPR_LDFLAGS="${PIPC_LDFLAGS} -Wl,--dynamic-linker=${dynamic_linker}"
-PIPR_LDLIBS="${PIPC_LDLIBS}"
-
-PIPT_CFLAGS="${PIPC_CFLAGS} -fPIC"
-PIPT_LDFLAGS="${PIPC_LDFLAGS} -pie -L${libdir} -rdynamic"
-PIPT_LDLIBS="${PIPC_LDLIBS}"
-
-PIPB_CFLAGS="${PIPT_CFLAGS}"
-PIPB_LDFLAGS="${PIPC_LDFLAGS} -pie -L${libdir} -rdynamic -Wl,--dynamic-linker=${dynamic_linker}"
-PIPB_LDLIBS="${PIPC_LDLIBS}"
-
-is_linking=true
-
-for i
-do
-	case $i in
-	-c|-E|-S)  is_linking=false; opts="${opts} $i";;
-	--piproot) pip_task=false;;
-	--piptask) pip_root=false;;
-	*)         opts="${opts} $i";;
-	esac
-done
-
-if ${pip_root}; then
-    if ${pip_task}; then
-	PIP_CFLAGS="${PIPB_CFLAGS}"
-	PIP_LDFLAGS="${PIPB_LDFLAGS}"
-	PIP_LDLIBS="${PIPB_LDLIBS}"
-    else
-	PIP_CFLAGS="${PIPR_CFLAGS}"
-	PIP_LDFLAGS="${PIPR_LDFLAGS}"
-	PIP_LDLIBS="${PIPR_LDLIBS}"
-    fi
-elif ${pip_task}; then
-   PIP_CFLAGS="${PIPT_CFLAGS}"
-   PIP_LDFLAGS="${PIPT_LDFLAGS}"
-   PIP_LDLIBS="${PIPT_LDLIBS}"
+if [[ -f ${libdir}/pip_preload.so ]]; then
+    preload=${libdir}/pip_preload.so;
 fi
 
-if ${is_linking}; then
-    echo ${CC} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${opts} ${PIP_LDLIBS};
-   ${CC} ${PIP_CFLAGS} ${PIP_LDFLAGS} ${opts} ${PIP_LDLIBS};
+for i; do
+    case $i in
+	-P|--process)
+	    if [[ x${preload} == x ]]; then
+		pip_mode=process:pipclone;
+	    else
+		pip_mode=process:preload;
+	    fi;;
+	-p|--process:preload)
+	    if [[ x${preload} == x ]]; then
+		echo "Unable to find PiP preload library (${preload})";
+		exit 1;
+	    else
+		pip_mode=process:preload;
+	    fi;;
+	-c|--process:pipclone)
+	    pip_mode=process:pipclone;;
+	-t|-T)
+	    pip_mode=pthread;;
+	-u|--help)
+	    flag_help=1;;
+	*)
+	    cmd="${cmd} $i";;
+    esac
+done
+
+function pipmode_help() {
+    echo $self "-P|-p|-c|-t [<command> ...]";
+    echo "    -P: process mode";
+    echo "    -p: process:preload mode";
+    echo "    -c: process:pipclone mode";
+    echo "    -t: pthread mode";
+}
+
+if [[ x${cmd} != x ]]; then
+    if [[ ${flag_help} == 1 ]]; then
+	pipmode_help;
+	exit 1;
+    elif [[ x${preload} == x ]]; then
+	PIP_MODE=${pip_mode} exec ${cmd};
+    else
+	PIP_MODE=${pip_mode} LD_PRELOAD=${preload}:$LD_PRELOAD exec ${cmd};
+    fi
 else
-    echo ${CC} ${PIP_CFLAGS} ${opts};
-   ${CC} ${PIP_CFLAGS} ${opts};
+    if [[ ${flag_help} == 1 ]]; then
+	pipmode_help;
+    else
+	echo "PIP_MODE=${pip_mode}";
+	export PIP_MODE=${pip_mode};
+    fi
 fi
