Some minor updates 1) change process name prefix char (pip_spawn.c) 2) echo environment variables (pipmode.in) 3) some cosmetic changes

diff --git a/bin/pipmode.in b/bin/pipmode.in
--- a/bin/pipmode.in
+++ b/bin/pipmode.in
@@ -55,10 +55,13 @@
 ### \subsection process	-T
 ### If specified, PiP will run with the 'thread' mode
 ###
+### \subsection process	-c
+### If specified, the current PIP_MODE environment is displayed
+###
 
 self=$0;
 prefix=@prefix@;
-libdir=${prefix}/lib/;
+libdir=${prefix}/lib;
 flag_help=0;
 
 if [[ -f ${libdir}/pip_preload.so ]]; then
@@ -75,7 +78,7 @@ for i; do
 	    fi;;
 	-p|--process:preload)
 	    if [[ x${preload} == x ]]; then
-		echo "Unable to find PiP preload library (${preload})";
+		echo "Unable to find PiP preload library";
 		exit 1;
 	    else
 		pip_mode=process:preload;
@@ -99,20 +102,33 @@ function pipmode_help() {
     echo "    -t: pthread mode";
 }
 
-if [[ x${cmd} != x ]]; then
-    if [[ ${flag_help} == 1 ]]; then
-	pipmode_help;
-	exit 1;
-    elif [[ x${preload} == x ]]; then
-	PIP_MODE=${pip_mode} exec ${cmd};
+if [[ ${flag_help} == 1 ]]; then
+    pipmode_help;
+    exit 1;
+fi
+
+if [[ x$pip_mode == x ]]; then
+    echo "PIP_MODE=${PIP_MODE}";
+    exit 0;
+fi
+
+export PIP_MODE=${pip_mode};
+
+if [[ x${preload} != x ]]; then
+    if [[ x${LD_PRELOAD} == x ]]; then
+	export LD_PRELOAD=${preload};
     else
-	PIP_MODE=${pip_mode} LD_PRELOAD=${preload}:$LD_PRELOAD exec ${cmd};
-    fi
-else
-    if [[ ${flag_help} == 1 ]]; then
-	pipmode_help;
-    else
-	echo "PIP_MODE=${pip_mode}";
-	export PIP_MODE=${pip_mode};
+	export LD_PRELOAD=${preload}:${LD_PRELOAD};
     fi
 fi
+
+if [[ x${cmd} != x ]]; then
+    exec ${cmd};
+else
+    if [[ x${preload} != x ]]; then
+	echo  "LD_PRELOAD=${LD_PRELOAD}";
+    fi
+    echo  "PIP_MODE=${PIP_MODE}";
+fi
+
+exit 0;
