Fix document bugs

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -73,12 +73,12 @@ documents:
 		echo ""; \
 		) | doxygen - >> doxygen-man713.log 2>&1; \
 	done
-	grep -e "warning" -e "error" doxygen-man713.log | cat
+	-@grep -e "warning" -e "error" doxygen-man713.log && ( echo "Doxygen failed"; exit 1; )
 	./markdown.sh "# Commands"  1 "-" > commands.in
 	./markdown.sh "# Functions" 3 "-" > functions.in
-	cat README.md.in commands.in functions.in Slides-md.md Author.md.in > README.md
-	cat README-man.doxy  README.md.in commands.in functions.in Author.md.in > README-man.md
-	cat README-html.doxy README.md.in Slides-html.md Author.md.in > README-html.md
+	cat README.md.in commands.in functions.in Slides-md.md Author-md.md > README.md
+	cat README-man.doxy  README.md.in commands.in functions.in Author-md.md > README-man.md
+	cat README-html.doxy README.md.in Slides-html.md Author-html.md > README-html.md
 	echo ==== README.md =====;
 	echo -n "" > doxygen-readme.log
 	( \
@@ -89,8 +89,8 @@ documents:
 		echo "STRIP_FROM_PATH = $(top_srcdir)"; \
 		printf "INPUT = README-man.md"; \
 		echo ""; \
-	) | doxygen - >> doxygen-readme.log 2>&1;
-	grep -e "warning" -e "error" doxygen-readme.log | cat
+	) | doxygen - >> doxygen-readme.log 2>&1
+	-@grep -e "warning" -e "error" doxygen-readme.log && ( echo "Doxygen failed"; exit 1; )
 	$(MAKE) -C latex-inuse
 	$(CP) README.md $(top_srcdir)
 	echo ==== html =====;
@@ -110,7 +110,7 @@ documents:
 		done <$$file; \
 	done | tr '\012' ' '; \
 	) | doxygen - >> doxygen-html.log 2>&1;
-	grep -e "warning" -e "error" doxygen-html.log | cat
+	-@grep -e "warning" -e "error" doxygen-html.log && ( echo "Doxygen failed"; exit 1; )
 	echo ==== mandb =====; \
 	if which mandb; then mandb ./man -c -u; fi
 .PHONY: doxygen
diff --git a/doc/latex-inuse/Makefile b/doc/latex-inuse/Makefile
--- a/doc/latex-inuse/Makefile
+++ b/doc/latex-inuse/Makefile
@@ -30,21 +30,16 @@
 
 LIBPIP = libpip-manpages
 
-all: $(LIBPIP).pdf
+pdf: all
 
-pdf: $(LIBPIP).pdf
-
-libpip-manpages.tex:
-	echo "Rerun configure"
-	exit 1
-
-$(LIBPIP).pdf: libpip-manpages.tex
+all :
 	./man-pages.sh
 	pdflatex $(LIBPIP) > /dev/null 2>&1
 	makeindex $(LIBPIP).idx > /dev/null 2>&1
 	pdflatex $(LIBPIP) > /dev/null 2>&1
 	latex_count=5 ; \
-	while egrep -s 'Rerun (LaTeX|to get cross-references right)' $(LIBPIP).log && [ $$latex_count -gt 0 ] ;\
+	while egrep -s 'Rerun (LaTeX|to get cross-references right)' $(LIBPIP).log && \
+		[ $$latex_count -gt 0 ] ;\
 	    do \
 	      echo "Rerunning latex...." ;\
 	      pdflatex $(LIBPIP) > /dev/null 2>&1 ;\
@@ -52,7 +47,12 @@ $(LIBPIP).pdf: libpip-manpages.tex
 	    done
 	makeindex $(LIBPIP).idx > /dev/null 2>&1
 	pdflatex $(LIBPIP) > /dev/null 2>&1
-	grep -e "LaTeX\ Warning" -e "Package\ natbib\ Warning" -e "undefined" -e "multiply\ defined" $(LIBPIP).log | cat
+	-@grep  -e "LaTeX\ Warning" \
+		-e "Package\ natbib\ Warning" \
+		-e "undefined" \
+		-e "multiply\ defined" \
+		$(LIBPIP).log \
+	&& ( echo "Latex failed"; exit 1; )
 
 clean:
 	$(RM) -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl
