expand_keyword 	and fix some doc related issues

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,4 +1,4 @@
-# $PIP_VERSION: Version 1.0$
+# $PIP_VERSION: Version 3.0.0$
 # $PIP_license: <Simplified BSD License>
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are
@@ -25,8 +25,8 @@
 # The views and conclusions contained in the software and documentation
 # are those of the authors and should not be interpreted as representing
 # official policies, either expressed or implied, of the PiP project.$
-# $RIKEN_copyright: 2018 Riken Center for Computational Sceience,
-# 	  System Software Devlopment Team. All rights researved$
+# $RIKEN_copyright: Riken Center for Computational Sceience,
+# System Software Development Team, 2016, 2017, 2018, 2019, 2020$
 
 top_builddir = ..
 top_srcdir = $(top_builddir)
@@ -37,9 +37,11 @@ MAN7_SRCS = README-html.md
 include $(top_srcdir)/build/var.mk
 include $(top_srcdir)/build/rule.mk
 
+all: install
+
 ### doxygen
 
-doxygen:
+documents:
 	-@$(RM) -r man latex html
 	echo -n "" > doxygen-man713.log
 	@doxy_dirs=$$(find .. -name .doxygen_latex -print | while read file; do \
@@ -71,13 +73,13 @@ doxygen:
 		echo ""; \
 		) | doxygen - >> doxygen-man713.log 2>&1; \
 	done
-	grep -e "warning" -e "error" doxygen-man713.log | cat
+	-@grep -e "warning" -e "error" doxygen-man713.log && ( echo "Doxygen failed"; exit 1; )
 	./markdown.sh "# Commands"  1 "-" > commands.in
 	./markdown.sh "# Functions" 3 "-" > functions.in
-	cat README.md.in commands.in functions.in Slides-md.md Author.md.in > README.md
-	cat README-man.doxy  README.md.in commands.in functions.in Author.md.in > README-man.md
-	cat README-html.doxy README.md.in Slides-html.md Author.md.in > README-html.md
-	echo ==== README.md =====;
+	cat README.md.in commands.in functions.in Slides-md.md Author-md.md > README.md
+	cat README-man.doxy  README.md.in commands.in functions.in Author-md.md > README-man.md
+	cat README-html.doxy README.md.in Slides-html.md Author-html.md > README-html.md
+	@echo ==== README.md =====;
 	echo -n "" > doxygen-readme.log
 	( \
 		cat "config-common.doxy"; \
@@ -87,11 +89,11 @@ doxygen:
 		echo "STRIP_FROM_PATH = $(top_srcdir)"; \
 		printf "INPUT = README-man.md"; \
 		echo ""; \
-	) | doxygen - >> doxygen-readme.log 2>&1;
-	grep -e "warning" -e "error" doxygen-readme.log | cat
+	) | doxygen - >> doxygen-readme.log 2>&1
+	-@grep -e "warning" -e "error" doxygen-readme.log && ( echo "Doxygen failed"; exit 1; )
 	$(MAKE) -C latex-inuse
 	$(CP) README.md $(top_srcdir)
-	echo ==== html =====;
+	@echo ==== html =====;
 	echo -n "" > doxygen-html.log
 	( \
 	cat "config-common.doxy"; \
@@ -108,29 +110,28 @@ doxygen:
 		done <$$file; \
 	done | tr '\012' ' '; \
 	) | doxygen - >> doxygen-html.log 2>&1;
-	grep -e "warning" -e "error" doxygen-html.log | cat
-	echo ==== mandb =====; \
+	-@grep -e "warning" -e "error" doxygen-html.log && ( echo "Doxygen failed"; exit 1; )
+	@echo ==== mandb =====; \
 	if which mandb; then mandb ./man -c -u; fi
 
-doc: doxygen
-
-all: doc
+all: install
 
 install:
-	echo "Installing .. " $(mandir)
-	$(MKDIR_P) $(mandir);
-	(cd ./man  && tar cf - . ) | (cd $(mandir) && $(RM) -r * && tar xf -)
-	echo "Installing .. " $(pdfdir)
-	$(MKDIR_P) $(pdfdir);
-	$(CP) ./latex-inuse/libpip-manpages.pdf $(pdfdir)
-	$(MKDIR_P) $(slidedir);
-	$(CP) ./slides/* $(slidedir)
-	echo "Installing .. " $(htmldir)
-	$(MKDIR_P) $(htmldir);
-	(cd ./html && tar cf - . ) | (cd $(htmldir) && $(RM) -r * && tar xf -)
+	@echo "Installing man pages ->" $(mandir)
+	@$(MKDIR_P) $(mandir);
+	@(cd ./man  && tar cf - . ) | (cd $(mandir) && $(RM) -r * && tar xf -)
+	@echo "Installing pdf ->" $(pdfdir)
+	@$(MKDIR_P) $(pdfdir);
+	@$(CP) ./latex-inuse/libpip-manpages.pdf $(pdfdir)
+	@$(MKDIR_P) $(slidedir);
+	@echo "Installing html ->" $(htmldir)
+	@$(MKDIR_P) $(htmldir);
+	@(cd ./html && tar cf - . ) | (cd $(htmldir) && $(RM) -r * && tar xf -)
+	@$(CP) ./slides/* $(slidedir)
+.PHONY: doc-install
 
 doc-reset:
-	git checkout man latex latex-inuse
+	git checkout man latex latex-inuse html slides
 .PHONE: doc-reset
 
 clean:
@@ -140,4 +141,5 @@ clean:
 	$(MAKE) -C latex-inuse clean
 
 veryclean: clean
-	$(RM) -r man latex html
+	$(RM) Slides-html.md
+	$(MAKE) -C latex-inuse veryclean
diff --git a/doc/latex-inuse/Makefile b/doc/latex-inuse/Makefile
--- a/doc/latex-inuse/Makefile
+++ b/doc/latex-inuse/Makefile
@@ -1,20 +1,45 @@
+# $PIP_VERSION: Version 3.0.0$
+# $PIP_license: <Simplified BSD License>
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are
+# met:
+#
+# 1. Redistributions of source code must retain the above copyright
+#    notice, this list of conditions and the following disclaimer.
+# 2. Redistributions in binary form must reproduce the above copyright
+#    notice, this list of conditions and the following disclaimer in the
+#    documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
+# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
+# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
+# The views and conclusions contained in the software and documentation
+# are those of the authors and should not be interpreted as representing
+# official policies, either expressed or implied, of the PiP project.$
+# $RIKEN_copyright: Riken Center for Computational Sceience,
+# System Software Development Team, 2016, 2017, 2018, 2019, 2020$
+
 LIBPIP = libpip-manpages
 
-all: $(LIBPIP).pdf
+pdf: all
 
-pdf: $(LIBPIP).pdf
-
-libpip-manpages.tex:
-	echo "Rerun configure"
-	exit 1
-
-$(LIBPIP).pdf: clean libpip-manpages.tex
+all :
 	./man-pages.sh
 	pdflatex $(LIBPIP) > /dev/null 2>&1
 	makeindex $(LIBPIP).idx > /dev/null 2>&1
 	pdflatex $(LIBPIP) > /dev/null 2>&1
 	latex_count=5 ; \
-	while egrep -s 'Rerun (LaTeX|to get cross-references right)' $(LIBPIP).log && [ $$latex_count -gt 0 ] ;\
+	while egrep -s 'Rerun (LaTeX|to get cross-references right)' $(LIBPIP).log && \
+		[ $$latex_count -gt 0 ] ;\
 	    do \
 	      echo "Rerunning latex...." ;\
 	      pdflatex $(LIBPIP) > /dev/null 2>&1 ;\
@@ -22,12 +47,17 @@ $(LIBPIP).pdf: clean libpip-manpages.tex
 	    done
 	makeindex $(LIBPIP).idx > /dev/null 2>&1
 	pdflatex $(LIBPIP) > /dev/null 2>&1
-	grep -e "LaTeX\ Warning" -e "Package\ natbib\ Warning" -e "undefined" -e "multiply\ defined" $(LIBPIP).log | cat
+	-@grep  -e "LaTeX\ Warning" \
+		-e "Package\ natbib\ Warning" \
+		-e "undefined" \
+		-e "multiply\ defined" \
+		$(LIBPIP).log \
+	&& ( echo "Latex failed"; exit 1; )
 
 clean:
-	rm -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl
-	rm -f *-inputs.tex
-	rm -f \#*\# *~
+	$(RM) -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl
+	$(RM) -f *-inputs.tex
+	$(RM) -f \#*\# *~
 
 veryclean:
-	rm -f $(LIBPIP).pdf
+	$(RM) -f $(LIBPIP).tex
